apiVersion: v1
kind: Service
metadata:
  name: nodecellar-service
spec:
  selector:
    app: nodecellar
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort

