apiVersion: v1
kind: ReplicationController
metadata:
  name: nodecellar
spec:
  replicas: 2
  selector:
    app: nodecellar
  template:
    metadata:
      name: nodecellar
      labels:
        app: nodecellar
    spec:
      containers:
      - name: nodecellar
        image: dfilppi/nodecellar:v2
        workingDir: /
        command: ["bash","start.sh"]
        ports:
        - containerPort: 3000
          hostIP: 0.0.0.0
        env:
        - name: NODECELLAR_PORT
          value: '3000'
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: '27017'
